version: "3"

services:
  container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Q-n-A
